version: "2"
plugins:
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
    config:
      config: ./.eslintrc.json
exclude_patterns:
  - "lib/*"
  - "tests/*"
  - "docs/*"
  - "vscode/*"
  - "**/*.md"
  - "**/*.yml"
  - "**/*.json"
  - "**/*.txt"
  - "babelrc"
  - ".gitignore"
  - ".gitmodules"
  - ".npmignore"
  - "yarn.lock"