image: node:latest
stages:
  - build
  - test
  - post_test
  - deploy
compile_ES5:
  stage: build
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
    - node_modules/
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - lib/
    expire_in: 1 hour
  script:
    - yarn install
    - ./node_modules/.bin/gulp compileES5
compile_quality:
  stage: compile
  script:
    - yarn compileQuality
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME-Quality"
    paths:
      - quality/
    expire_in: 1 hour
test_ES5_Node_6:
  stage: test
  image: node:6
  dependencies:
    - compile_ES5
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn install
    - yarn test
test_ES5_Node_8:
  stage: test
  image: node:8
  dependencies:
    - compile_ES5
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn install
    - yarn test
test_ES5_Node_10:
  stage: test
  image: node:10
  dependencies:
    - compile_ES5
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn install
    - yarn test
test_ES5_Node_latest:
  stage: test
  image: node:latest
  dependencies:
    - compile_ES5
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn install
    - "./node_modules/.bin/nyc -x \"**/lib/es6/**/*.js\" -x \"**/src/**/*.js\" -x \"**/tests/**/*.js\" yarn test"
  artifacts:
    paths:
      - .nyc_output/
code_coverage:
  stage: post_test
  image: node:latest
  allow_failure: true
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - node_modules/
    policy: pull
  script:
    - "./node_modules/.bin/nyc report --reporter=\"text-summary\" --reporter=\"lcov\""
  dependencies:
    - test_ES5_Node_latest
  artifacts:
    paths:
      - coverage/lcov-report/
    expire_in: 1 day
  coverage: '/^Statements\s*:\s*([^%]+)/'
code_quality:
  image: docker:latest
  stage: post_test
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  dependencies:
    - compile_quality
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD/quality"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]
dependency_scanning:
  image: docker:latest
  stage: post_test
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    paths: [gl-dependency-scanning-report.json]
publish_NPM:
  stage: deploy
  only:
    - tags
    - triggers
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm publish --scope=@openrailuk --access=public
