image: node:latest
stages:
  - install
  - compile
  - test
install:
  stage: install
  script:
    - yarn install
  cache:
    paths:
    - node_modules/
compile ES5:
  stage: compile
  script:
    - yarn compile
  cache:
    paths:
    - node_modules/
    - lib/
test:
  stage: test
  script:
    - yarn coverage
  artifacts:
    paths:
      - mochawesome-report/mochawesome.html
  coverage: '/^Statements\s*:\s*([^%]+)/'
