stages:
  - compile
  - test

compile:
  image: node:latest
  stage: compile
  script:
    - yarn compile

test:
  image: node:latest
  stage: test
  cache:
    paths:
    - node_modules/
  script:
    - yarn install
    - yarn coverage
  artifacts:
    paths:
      - mochawesome-report/mochawesome.html
