stages:
 - build
 - test

build:
  image: node:latest
  stage: build
  cache:
    paths:
    - node_modules/
  script:
   - yarn install
   - yarn build

test:
  image: node:latest
  stage: build
  cache:
    paths:
    - node_modules/
  script:
   - yarn install
   - yarn test