stages:
  - test

test:
  image: node:latest
  stage: test
  cache:
    paths:
    - node_modules/
  script:
    - yarn install
    - yarn coverage
  artifacts:
    paths:
      - mochawesome-report/mochawesome.html
      - mochawesome-report/mochawesome.json
