image: node:latest
cache:
  paths:
  - node_modules/
  - lib/
stages:
  - install
  - compile
  - test
  - code quality
install:
  stage: install
  script:
    - yarn install
compile ES5:
  stage: compile
  script:
    - yarn compile
test:
  stage: test
  script:
    - yarn coverage
  artifacts:
    paths:
      - mochawesome-report/mochawesome.html
  coverage: '/^Statements\s*:\s*([^%]+)/'
code quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    paths: [gl-code-quality-report.json]