image: node:latest
cache:
  paths:
  - node_modules/
  - lib/
stages:
  - install
  - compile
  - test
install:
  stage: install
  script:
    - yarn install
compile:
  stage: compile
  script:
    - yarn compile
test:
  stage: test
  script:
    - yarn coverage
  artifacts:
    paths:
      - mochawesome-report/mochawesome.html
  coverage: '/^Statements\s*:\s*([^%]+)/'
