language: node_js
matrix:
  include:
  - node_js: '6'
    env:
    - UNIT=test
  - node_js: '7'
    env:
    - UNIT=test
  - node_js: '8'
    env:
    - UNIT=test
  - node_js: '9'
    env:
    - UNIT=test
  - node_js: node
    env:
    - UNIT=test
script:
- npm run $UNIT
env:
  global:
  - NODE_ENV=testing
  - secure: efemKiDRRuyLzdedXvx2J5o3spKH2esu4D7ig6hcOqErkwWfnnl/5VkhJC90QF7qVJ4nvePE84IXEQfzRxWLEqWs+B+Q0kOfPoz2GKMOsN5F/dib59OxFXgOe1yC9YwUokS34yFEPSLgdkeuUOFIL+IXCzKGJuTJCbfKW8AgHCHrH1uTymDjzxUOLkSz/N3mzPT5Nxf6eEXpoQBDOR0LK+eN0y0ueH3Pxxn07i4mckN4oJRhcnledHvYTbo1qbUDLLu/7v3bDRJSJyIUoaVxhuZfjK8+HLjucWuRPZyLO1zRDmFuHzThioj537xtX14b+vSufG0xvWqiwJg6+Z/wi8FqquN9aOtqPpt4E60MjsizXI1lsursowyUxe0txpLpE5azHCOyKxg6XFd3xIGC+pf/J7oFndCmUHwxImUpv+IIqWjjSDNaqB9Ga0i2fZ/Dz7e/fMippcCQX93htTXKgOo+l1Umwm6GzCeMWdNRGuIzW8ZHZY067d+dXyT8pFLanfl/3rfMiKb8Kk6erLXoQ68bXVwIriARFDtJLEz5nLURu/XrePhrA1l9QlPtlZ+KtsI8/xMqGpVWw0ABo9k6iv0r+MrO77vubEnDmq5uotcbcwoZ4c8eaQizIY6goayk/qZLMEFxn/eZdWxNSxYtpn6HjmUoYxcKJI2GcqYmsU4=
  - secure: Oih/M+jR3FkyUTVzRleLBBoyhBelN2QxFyaXu4dh/TNZMHhapTY/E+FKOr+k7x4LNbiq1KwUP7HTbla4VQLgTHfTL23uOQischokvv1rZOd4XP32eppcmZThJ4tSnggcllT/fLovH3X+DB2PDEFgQinuBTvPbmxBatr55y/6NScqkbecKiw96LM84gkxetA/cdCmZWpQ8z5RPpdWx2T9abodPEJTPfXk5XNewZJYnkj/33/AjVrXdPG5RjayYG40ISbLGq2RnTofiPcIkUBuJu1zavM/e9omZy4zcie79b2xMxQBCSn4g5cte6vT72n7BSjGXzKzJYwUyhhwvf0royWxbWFfJTfawctEr9SNwixWD1a/3iKIgzp32CGWNhzWDuqGsJcAeo4WLKhRFnn1qPM2/VLp2qNRtd3fkTpBjxUhNjjDoA1x+25cMjKjyNdTFR1v/bwR1Ij5Ms+KbiODApxUL0J054Xo+wXRKKRWF1SU3KEXyhM/ubUP+j0GqMfYdiV9ZHgmuqLaHQqrxP7zzBxb7PATYXYmFDT/ZD/6w3PUCi06/SKinsrulZGA47QFHHUfPIgUa+f974kR5vGQs0A9V6K1j9Lqc0JrmjoeK6HK+w9KKW4uymz0asgiHB0OI1oGry6FOz+k7oFM9MOOhqj1GRHHXTPd8Y1tSuB58sg=
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- greenkeeper-lockfile-update
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
- greenkeeper-lockfile-upload
before_install: yarn global add greenkeeper-lockfile@1
notifications:
  slack:
    secure: DTT9goyxrOD6DR2dQYd4NNoCSWzqROGrvt+4yyCy3YYeyMNGPclRNemYa8+OZBorHUgzu4gI/5+NJ35G/FU7x5WXLsr+j+/KL+VCWeSKI02g+JBNaMWjaL+L/fqoCNlyoHS6Us7qU4lOfuoZSHABFlmgtI5MqcEzPxeYqZKALZTwyvSSZULiStlkyIdORORRthomrAr/ljF0urabRkvalpIoF8QY0qNy1ncAZBFPteDee5outYfw0CRG08oJwZBdTsat5a9UVVbMIi9a1auYkERlZvA+ZM/WfJLW8wwc47Si7udx6ErJul8Yzo9zNTRJR1DZNwUMoT3fXOf8YFnyfWHe3gJoNzMxRJIwb/4W4ggyHGsELTCzUj6iyVgiCeKLHNNhmxDYUvnMQr4/FapIny9iAbjDwhtMfZMQgi2jRKN55N0LeFv9wYheocyYM87j2POpz17MVQwvlys/7BJfkjD2IQ8uj/QEveMbgIn2+DvkretNglWGKPd6gmuoME58VrHFHMwhs3cS5TjVDin/zE6vXpeuFjDwf4lfBKrlooSiS9ATu9i/c0SIqVKhfM4nE63ruuPyfYGIFa+Njs3h0C6Hem9NB4EoPx/JvYDRHuiFQY66Gg5MWouyxnqE2Cm/g4+tWtqCysfM/vK6tg08CWs0osllMnO6YsFCjBF9re4=
deploy:
  provider: npm
  email:
    secure: lzrO9icBs47SokNicH65R6uDq0RCDeF7CySrDFic7knDX7dHuRUHzxv/btJw+dw4SYQDiJZk7TgQdJJ54+cVhn8UqD+ROzdg4rROex/1NbK7YK/ACF9G+NYzhLRae97CIu7s/AnOwruhcpZ2hdPKPRbgbPjf4cReiNnAYN/FuQXQmtEhuO4+XOfYwPOFhGer4GeG3Unhe1tbhLcP+ndi7vbqiBasFWVV4XwDAbusSSP2PaiHNYYpPb2luYktxeJonEsA9Jd19vk2URvBUWyVRgETfg/NdKQzNC8mfNdlVKLpLr9VE1a4kq0LYrHP0+NxwST9bqUbc12afk3h53naq+rB5jtUImHUZpnFQnwVSdEwRWcYmzbhZ/6nrtwHMpmFObDZ7b0ihiKblqoY9n/YxRzjLfB5SkX1m0mx5/CnFG+GnB74hppaG+M1sIGAImgtpP6gxw3mxh8+EKIYL6+9im6rF6Rid+y6bzcmxM/fmP+BIrCAHt37fx2VE26WOXbLmELoaBLZSbYNJFcsy5/c2V3ZyCLWJbN2hHjngtoDIsMoWjDCGrnzSLnyf2MEWomLu4pcxEDpfeFEcc94f3jdsQFNUcJhrNdfOI3nMOT9fmgz0ruv//7oA+dwMotNSbbgfPuz+vs1z58mrKGdED8Y2TD4Ipb5YCVSVuIZH2Bbd5s=
  api_key:
    secure: bdWSI0onwe9Mzyc5OcD1cL7RiiD7aB/fsa8wmSkgDLoYY4t3ENr4DCmjU0uIHshXJaLYWIuQqKu9Y7291UDB0OVH+Jd5vimlDaWD934cGR11/GCHEAXZYnlH8C4QOt+aKBJf3OxDimgvn1eDQ+tRtfmVq4PEA5cHlmnU3SUPsSVvULddHnZrFN8VccnsuKwL8fkG+gisL3oX7c28j3hPL9ylb4qq9DhdEI9Qa/7wYQ5W/PG6sK5BrPzUAwVGraI+BP/9LmA3WwSmlpy4EzpZ897q3N1MGsqf5rvwNVcovoIYRdKKHu0wOkgObLil228Es8mwf4MQNuPQJ/bbNwi0goihKQf7t+/h2mRdmSiqXXx5GNLFXSxEb+MnXx5K2xpSwd2ibCFD+3DKLuWOXJ85P4CqfsOlE2nC+H5wqW16kP2e0+yDfyrH7K7cUprUORnw5fLEme7lHIaxpGi1KWxTSGgRSbr6nuuOGLv2912hQ6/Oc1bCBnqVbCDFa1+ol4s/Yh9cK9YdDxBL5lMpeG4ZqIUnVmP/ORYlb4/No00p56QwwaHuG8d+TSlMhXtwncrtaw4UxhaGNYtXeTvHeTfTCFxBaQdT+RxPNyq5hCzcGnS+120L4hQQ6dMIjINRTll3/zYNCm6Y8N6/8HkQuaalxJ4QFMm/vA094wUiSKtBb6Y=
  on:
    tags: true
